rango/urls.py
from django.urls import path
from rango import views
from rango.views import CategorySuggestionView,AboutView,AddCategoryView,ShowCategoryView,AddPageView,GotoURLView,RegisterProfileView,ProfileView,ListProfilesView,LikeCategoryView

app_name = 'rango'

urlpatterns = [
	path('',views.index, name='index'),
	path('about/', AboutView.as_view(), name='about'),
	path('category/<slug:category_name_slug>/', ShowCategoryView.as_view(), name='show_category'),
	path('add_category/', AddCategoryView.as_view(), name='add_category'),
	path('category/<slug:category_name_slug>/add_page/', AddPageView.as_view(), name='add_page'),
    # path('search/',views.search, name='search'),
    path('goto/',GotoURLView.as_view(), name='goto'),
    path('register_profile/', RegisterProfileView.as_view(), name='register_profile'),
    path('profile/<username>/', ProfileView.as_view(), name='profile'),
    path('profiles/', ListProfilesView.as_view(), name='list_profiles'),
    path('like_category/',LikeCategoryView.as_view(), name='like_category'),
    path('suggest/', CategorySuggestionView.as_view(), name='suggest' ),
]

tango_with_django_project/urls.py
from  django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path
from django.urls import include, reverse
from rango import views
from registration.backends.simple.views import RegistrationView

class MyRegistrationView(RegistrationView):
    def get_success_url(self, user):
        return reverse('rango:register_profile')

urlpatterns = [
	path('',views.index, name='index'),
	path('rango/',include('rango.urls')),
    #The above maps any URLs starting with rango/ to be handled by rango
	path('admin/', admin.site.urls),
    path('accounts/register/',
         MyRegistrationView.as_view(),
         name= 'registration_register'),
         
    #configuration with registration redux
	path('accounts/', include('registration.backends.simple.urls'))

] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

rango/models.py
from django.db import models
from django.template.defaultfilters import slugify

from django.contrib.auth.models import User

# Create your models here.
class Category(models.Model):
	name = models.CharField(max_length=128, unique=True)
	NAME_MAX_LENGTH = 128
	views= models.IntegerField(default=0)
	likes = models.IntegerField(default=0)
	
	#adding a slug field to slugify URLS.
	#always add the unique attribute after following creating your Database and populating it.
	#else there will be migration issues.
	slug = models.SlugField(unique=True) 


	def save(self, *args, **kwargs):
		self.slug = slugify(self.name)
		super(Category, self).save(*args, **kwargs)


	#Meta class just allows for correct plural form of model names in Django admin panel
	class Meta:
		verbose_name_plural = 'Categories'

	#provides a string representation of of the Userprofile class 
	def __str__(self):
		return self.name


class Page(models.Model):
	TITLE_MAX_LENGTH =128
	URL_MAX_LENGTH = 200

	category = models.ForeignKey(Category, on_delete=models.CASCADE)
	title = models.CharField(max_length=TITLE_MAX_LENGTH)
	url = models.URLField()
	views = models.IntegerField(default=0)

	#Meta class just allows for correct plural form of model names in Django admin panel
	class Meta:
		verbose_name_plural ='Pages'
	
	#provides a string representation of of the Page class 
	def __str__(self):
		return self.title
	

class UserProfile(models.Model):
	#This line is required to link  a UserProfile to a User model instance.
	user = models.OneToOneField(User, on_delete = models.CASCADE)

	#The additional attributes we wish to include.
	website = models.URLField(blank=True)
	picture = models.ImageField(upload_to='profile_images', blank=True)

	#provides a string representation of of the Userprofile class 
	def __str__(self):
		return self.user.username

	

rango/forms.py
from django import forms
from rango.models import Page, Category,UserProfile

from django.contrib.auth.models import User

#Meta: describes additional attributes about the class.
class CategoryForm(forms.ModelForm):
	name = forms.CharField(max_length=Category.NAME_MAX_LENGTH, help_text='Please enter the category name.')
	views = forms.IntegerField(widget=forms.HiddenInput(),initial = 0)
	likes = forms.IntegerField(widget=forms.HiddenInput(), initial=0)
	slug = forms.CharField(widget=forms.HiddenInput(), required=False)

	#An inline class to provide additional information on the form.
	class Meta:
		#Provide an association betwen the ModelForm and a model
		model = Category
		fields = ('name',)

class PageForm(forms.ModelForm):
	title = forms.CharField(max_length=Page.TITLE_MAX_LENGTH, help_text='Please enter the title of the page.')
	url = forms.URLField(max_length=Page.URL_MAX_LENGTH, help_text='Please enter the URL of the page.')
	views = forms.IntegerField(widget=forms.HiddenInput(), initial = 0)

	class Meta:
		#Provide association between a the ModelForm and a model
		model = Page
		#What fields do we want to include in our form?
		#This way we don't need every field in the model present
		#Some fields may allow NULL values; we may not want to include them.
		#Here, we are hiding the foreign key
		#we can either exclude the category field from the form,
		
		exclude =('category',)
		#or specify the fields to include (don't include the category field).
		#fields = ('title', 'url', 'views')

		def clean(self):
			cleaned_data = self.cleaned_data
			url = cleaned_data.get('url')

			#if url is not empty and doesn't start with 'http://',
			#then prepend 'http://'
			if url and not url.startswith('http://'):
				url = f'http://{url}'
				cleaned_data['url'] = url

			return cleaned_data
		

class UserForm(forms.ModelForm):
	password = forms.CharField(widget=forms.PasswordInput())

	class Meta:
		model = User
		#fields indicate which fields on the model should be present when form has been successfully rendered
		fields = ('username', 'email', 'password',)


class UserProfileForm(forms.ModelForm):
	class Meta:
		model = UserProfile
		#fields indicate which fields on the model should be present when form has been successfully rendered
		fields = ('website', 'picture',)

rango/views.py
from django.contrib.auth import authenticate, login, logout
from django.shortcuts import render,redirect,get_object_or_404
from django.http import HttpResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from datetime import datetime
from django.views import View
from django.utils.decorators import method_decorator

#import view
from rango.bing_search import run_query

#importing models
from rango.models import Category, Page, UserProfile
from django.contrib.auth.models import User
#import forms
from rango.forms import CategoryForm,PageForm, UserForm, UserProfileForm

def index(request):
	# Query the database for a list of All categories currently stored.
	# Order the categories by the number of likes in descending order.
	# Retrieve the top 5 only -- or all if less than 5.
	# Place the list in our context_dict dictionary (with our boldmessage!).
	# that will be passed to the template engine.
	category_list = Category.objects.order_by('-likes')[:5]
	#retirve top 5 most viewed pages
	page_list = Page.objects.order_by('-views')[:5]

	context_dict ={}
	context_dict['boldmessage'] = 'Crunchy, creamy, cookie, candy, cupcake!'
	context_dict['categories'] = category_list
	context_dict['pages'] = page_list
	
	visitor_cookie_handler(request)
	# context_dict['visits'] = request.session['visits']

	#obtain our response object early so we can add cookie information
	response = render(request, 'rango/index.html', context = context_dict)
	# Call the helper function to handle the cookies
	return response



class AboutView(View):
	def get(self, request):
		context_dict ={}
		visitor_cookie_handler(request)
		context_dict['visits'] = request.session['visits']

		return render(request,'rango/about.html',context=context_dict)

class ShowCategoryView(View):
	context_dict ={}
	query= None
		
	@method_decorator(login_required)
	def post(self, request, category_name_slug):
		self.query = request.POST.get('query')
		if self.query:
			pages = Page.objects.filter(category__slug=category_name_slug, title__icontains=self.query)
			self.context_dict['result_list'] = pages
			self.context_dict['query'] = self.query
		
		return render(request, 'rango/category.html', self.context_dict)

	def get(self, request, category_name_slug):
		try:
			# can we find a category name slug wiht the given name? If we can't, the .get() method raises a DoesNotExist exception.
			# The .get() method returns one model instance or raises an exception.
			category = Category.objects.get(slug=category_name_slug)
			# Retrieve all of the associated pages.
			# The filter() will return a list of page objects or an empty list.	
			pages = Page.objects.filter(category=category)
			ordered_pages = pages.order_by('-views')
			# Adds our results list to the template context under names pages.
			self.context_dict['pages'] = ordered_pages
			# We also add the category objects from the database to the context dictionary.We'll use this in the template to verify  category exists
			self.context_dict['category'] = category
		except Category.DoesNotExist:
			# We get here if we didgn't find the specified category. Don't do anything
			# the template will display the "no category" message for us.
			self.context_dict['category'] = None
			self.context_dict['pages'] = None

		#Go render the response and return it to the client.
		return render(request, 'rango/category.html', self.context_dict)


class AddCategoryView(View):
	@method_decorator(login_required)
	def get(self, request):
		form = CategoryForm()
		return render(request, 'rango/add_category.html',{'form':form})

	@method_decorator(login_required)
	def post(self, request):
		form = CategoryForm(request.POST)

		if form.is_valid():
			form.save(commit=True)
			return redirect(reverse('rango:index'))
		else:
			print(form.errors)
		
		return render(request, 'rango/add_category.html', {'form':form})
		


class AddPageView(View):
	@method_decorator(login_required)	
	def get(self,request, category_name_slug):
		try:
			category = Category.objects.get(slug=category_name_slug)
		except Category.DoesNotExist:
			category = None
   		# You cannot add a page to a Category that does not exist...
		if category is None:
			return redirect('/rango/')
		
		form = PageForm()
		context_dict ={'form':form, 'category':category}
		return render(request, 'rango/add_page.html', context=context_dict)

	@method_decorator(login_required)
	def post(self,request,category_name_slug):
		try:
			category = Category.objects.get(slug=category_name_slug)
		except Category.DoesNotExist:
			category = None
   		# You cannot add a page to a Category that does not exist...
		if category is None:
			return redirect('/rango/')
		
		form = PageForm(request.POST)

		if form.is_valid():
			if category:
				page = form.save(commit=False)
				page.category = category
				page.views = 0
				page.save()
				
				return redirect(reverse('rango:show_category',
										kwargs={'category_name_slug':
												category_name_slug}))
		else:
			print(form.errors)


		context_dict = {'form': form, 'category': category}
		return render(request, 'rango/add_page.html', context=context_dict)	
		

# @login_required
# def restricted(request):
# 	return render(request, 'rango/restricted.html')


#Use the login_required() decorator to ensure only those logged in can  access the view
# @login_required
# def user_logout(request):
# 	# Since we know the user is logged in, we can now just log them out.
# 	logout(request)
# 	# Take the user back to the homepage.
# 	return redirect(reverse('rango:index'))


# A helper method
def get_server_side_cookie(request, cookie, default_val= None):
	val = request.session.get(cookie)
	if not val:
		val = default_val
	return val

#a helper function to calculate the number of visits a user makes to a page.
def visitor_cookie_handler(request):
	# Get the number of visits to the site.
	# We use the COOKIES.get() function to obtain the visits cookie.
	# If the cookie exists, the value returned is casted to an integer.
	# If the cookie doesn't exist, then the default value of 1 is used.
	visits = int(get_server_side_cookie(request,'visits', '1'))
	last_visit_cookie = get_server_side_cookie(request,'last_visit', str(datetime.now()))
	last_visit_time = datetime.strptime(last_visit_cookie[:-7], '%Y-%m-%d %H:%M:%S')


	#if it's more than a day since the last visit..
	if(datetime.now() - last_visit_time).days > 0:
		visits = visits + 1
		#Update the last visit cookie now that we have update the count.
		request.session['last_visit'] = str(datetime.now())
	else:
		# set the last visits cookie
		request.session['last_visit'] = last_visit_cookie
	
	#Update/set the visits cookie
	request.session['visits'] = visits

#this helper function takes the request and response objects - because we want to be able to access the incoming cookies
#from the request and add or update the cookies in the response.


# def search(request):
# 	#result_list = []
# 	context_dict ={}
# 	context_dict['result_list'] =[]
# 	print("Checking what is in request",request)
# 	if request.method == 'POST':
# 		query = request.POST['query'].strip()
# 		print("Query", query)
# 		if query:
# 			#Run our Bing function to get the results list!
# 			# result_list  = run_query(query)
# 			context_dict['result_list'] = run_query(query)
# 			context_dict['query'] = query
# 			print(query)

# 	return render(request, 'rango/search.html',context_dict)




class GotoURLView(View):
	def get(self, request):
		try:
			page_id = request.GET.get('page_id')
			page = get_object_or_404(Page, id=page_id)
			page.views +=1
			page.save()
			return redirect(page.url)
		except Page.DoesNotExist:
			return redirect(reverse('rango:index'))


class RegisterProfileView(View):
	@method_decorator(login_required)
	def get(self, request):
		form = UserProfileForm()
		context_dict = {'form':form}
		return render(request, 'rango/profile_registration.html', context_dict)

	@method_decorator(login_required)
	def post(self, request):
		form = UserProfileForm(request.POST, request.FILES)

		if form.is_valid():
			user_profile = form.save(commit=False)
			user_profile.user = request.user
			user_profile.save()

			return redirect(reverse('rango:index'))
		else:
			print(form.errors)

		context_dict = {'form': form}
		return render(request, 'rango/profile_registration.html', context_dict)



class ProfileView(View):
	def get_user_details(self, username):
		try:
			user = User.objects.get(username = username)
		except User.DoesNotExist:
			return None
		user_profile = UserProfile.objects.get_or_create(user=user)[0]
		form = UserProfileForm({'website': user_profile.website,
			  					'picture': user_profile.picture})
		
		return(user, user_profile, form)
	
	@method_decorator(login_required)
	def get(self,request, username):
		try:
			(user, user_profile, form) = self.get_user_details(username)
		except TypeError:
			return redirect(reverse('rango:index'))
		
		context_dict = {'user_profile': user_profile,
		  				'selected_user': user,
		  				'form': form}
		
		return render(request,'rango/profile.html', context_dict)
	
	#in the post we are saving the new details after edit. 
	@method_decorator(login_required)
	def post(self, request, username):
		try:
			(user, user_profile, form) = self.get_user_details(username)
		except TypeError:
			return redirect(reverse('rango:index'))
		
		form = UserProfileForm(request.POST, request.FILES, instance=user_profile)

		if form.is_valid():
			form.save(commit=True)
			return redirect('rango:profile', user.username)
		else:
			print(form.errors)

		context_dict = {'user_profile': user_profile,
		  				'selected_user': user, 
		  				'form': form}
		
		return render(request, 'rango/profile.html', context_dict)



class ListProfilesView(View):
	@method_decorator(login_required)
	def get(self, request):
		profiles = UserProfile.objects.all()
		return render(request,
					  'rango/list_profiles.html',
					  {'userprofile_list': profiles})

templates/rango/about.html
{% extends 'rango/base.html' %}
{% load staticfiles %} <!-- New line-->
{% block title_block %}
	About Rango
{% endblock %}
{% block body_block %}
		<h1>Rango says... </h1>
		<p>"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."</p>
					
		<div>
			hey there partner! <br />
			<strong>{{ boldmessage }}</strong><br />
			Visits: {{ visits }}
			<button class="btn btn-primary" id="about-btn">
				Click me - I run on vanilla JavaScript!
			</button>
			<img src="{% static 'images/rango.jpg' %}" alt="Photo of Rango"/>
		</div>
		<div>
			<img src="{{MEDIA_URL}}cat.jpg"
				alt="Picture of a Cat" /> <!-- New line -->
		</div>
{% endblock %}

templates/rango/add_category.html
{% extends 'rango/base.html' %}
{% load staticfiles %}

{% block title_block %}
Add a Category
{% endblock %}

{% block body_block %}
<div class="jumbotron p-4">
	<div class="container">
		<h1 class="jumbotron-heading">Add a Category</h1>
	</div>
</div>

<div class="container">
	<div class="row">
		<form id="category_form" method="post" action="{% url 'rango:add_category' %}">
			{% csrf_token %}
			{% for hidden in form.hidden_fields %}
				{{hidden}}
			{% endfor %}
			{% for field in form.visible_fields %}
				{{ field.errors}}
				{{ field.help_text}} <br />
				{{ field }} <br />
				<div class="p-2"></div>
			{% endfor %}
			<br />
			<button class="btn btn-primary" type="submit" name="submit">
				Add Page
			</button>
			<div class="p-5"></div>
		</form>
	</div>
</div>
{% endblock %}

templates/rango/add_page.html
{% extends 'rango/base.html' %}
{% load staticfiles %}

{% block title_block %}
Add a Page
{% endblock %}

{% block body_block %}
<div class="jumbotron p-4">
	<div class="container">
		<h1 class="jumbotron-heading">Add a Page to {{category.name}}</h1>
	</div>
</div>

<div class="container">
	<div class="row">
			<form id="page_form" method="post" action="{% url 'rango:add_page' category.slug %}">
				{% csrf_token %}
				{% for hidden in form.hidden_fields %}
					{{ hidden }}
				{% endfor %}
				{% for field in form.visible_fields %}
					{{ field.errors }}
					{{ field.help_text }}<br />
					{{ field }}<br />
					<div class="p-2"></div> 
				{% endfor %}
				<br />
				<button class="btn btn-primary" type="submit" name="submit">
					Add Page
				</button>
				<div class="p-5"></div>
			</form>
	</div>
</div>
{% endblock %}

templates/rango/base-old.html
<!DOCTYPE html>
{% load staticfiles%}
{% load rango_template_tags %}

<html>
	<head lang="en">
		<meta  charset="UTF-8"/>
		<title>
			Rango -
			{% block title_block %}
				How to Tango with Django!
			{% endblock %}
		</title>
	</head>
	<body>
		<!--- Page Specific content goes here-->
		<div>
		{% block body_block %}
		{% endblock %}
		</div>
		<div>
			{% block sidebar_block %}
				{% get_category_list category%}
			{% endblock %}
		</div>
		<hr />
		<div>
			<ul>
				{% if user.is_authenticated %}
				<!-- Show these links when the user is logged in -->
				<li><a href="{% url 'rango:restricted' %}">Restricted Page</a></li>
				<li><a href="{% url 'auth_logout' %}?next={% url 'rango:index' %}">Logout</a></li>
				<li><a href="{% url 'rango:add_category' %}">Add New Category</a></li>
				<li><a href="{% url 'auth_password_change' %}?next={% url 'auth_password_change_done' %}">Change password</a></li>
				{% else %}
				<!-- Show these links when the user is NOT logged in -->
				<li><a href="{% url 'registration_register' %}">Sign Up</a></li>
				<li><a href="{% url 'auth_login' %}">Login</a></li>
				{% endif %}
				<!-- Outside the conditional statements, ALWAYS show -->
				<li><a href="{% url 'rango:about' %}">About</a></li>
				<li><a href="{% url 'rango:index' %}">Index</a></li>
			</ul>
		</div>
	</body>
</html>

templates/rango/base.html
<!DOCTYPE html>
{% load staticfiles %}
{% load rango_template_tags %}
<html lang="en">
    <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Jekyll v3.8.5">
    <link rel="icon" href="{% static 'images/favicon.ico' %}">
    <title>
        Rango - {% block title_block %}How to Tango with Django!{% endblock %}
    </title>
    
    <!-- Bootstrap core CSS -->
    <link href="https://getbootstrap.com/docs/4.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
    
    <!-- Custom styles for this template -->
    <link href="https://getbootstrap.com/docs/4.2/examples/dashboard/dashboard.css" rel="stylesheet">
    </head>
    
    <body>
        <header>
            <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark p-0">
                <a class="navbar-brand p-2" href="{% url 'rango:index' %}">Rango</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                
                <div class="collapse navbar-collapse" id="navbarCollapse">
                    <ul class="navbar-nav mr-auto">
                        <li class="nav-item"><a class="nav-link" href="{% url 'rango:index' %}">Home</a></li>
                        <li class="nav-item "><a class="nav-link" href="{% url 'rango:about' %}">About</a></li>
                        {% if user.is_authenticated %}
                        <li class="nav-item"><a class="nav-link" href="{% url 'auth_logout' %}?next=/rango/">Logout</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'rango:add_category' %}">Add Category</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'auth_password_change' %}">Change Password</a></li>
						<li class="nav-item"><a class="nav-link" href="{% url 'rango:profile' user.username %}">Profile</a></li>
						<li class="nav-item"><a class="nav-link" href="{% url 'rango:list_profiles' %}">List Profile</a></li>
						{% else %}
                        <li class="nav-item"><a class="nav-link" href="{% url 'registration_register' %}">Register Here</a></li>
                        <li class="nav-item "><a class="nav-link" href="{% url 'auth_login' %}">Login</a></li>
                        {% endif %}
                    </ul>
                </div>
            </nav>
        </header>
        
        <div class="container-fluid">
            <div class="row">
                <nav class="col-md-2 d-none d-md-block bg-light sidebar">
					<div class="w-75 ml-3">
						<input type="search" 
							id="search-input" c
							lass="form-control ds-input" 
							placeholder="Search..."/>
					</div>
                    <div class="sidebar-sticky" id="categories-listing">
                    {% block sidebar_block %}
                        {% get_category_list category %}
                    {% endblock %}
                    </div>
                </nav>
                
                <main role="main" class="col-md-9  ml-sm-auto col-lg-10 px-4">		
                    {% block body_block %}{% endblock %}
                    
                    <!-- FOOTER -->
                    <footer>
                        <p class="float-right"><a href="#">Back to top</a></p>
                        <p>&copy; 2020 Tango With Django 2 &middot; <a href="#">Privacy</a> &middot; <a href="#">Terms</a></p>
                    </footer>
                </main>
            </div>
        </div>
        
        <!-- Bootstrap core JavaScript -->
        <!-- Placed at the end of the document so the pages load faster -->
		<script src="{% static 'js/rango-jquery.js' %}" crossorigin="anonymous"></script>
		<script>window.jQuery || document.write('<script src="https://getbootstrap.com/docs/4.2/assets/js/vendor/jquery-slim.min.js"><\/script>')</script><script src="https://getbootstrap.com/docs/4.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-zDnhMsjVZfS3hiP7oCBRmfjkQC4fzxVxFhBx8Hkz2aZX8gEvA/jsP3eXRCvzTofP" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/feather-icons/4.9.0/feather.min.js"></script>
        <script src="https://getbootstrap.com/docs/4.2/examples/dashboard/dashboard.js"></script>
    </body>
</html>

templates/rango/categories.html
<ul class="nav flex-cloumn">
	{% if categories %}
		{% for c in categories %}
			{% if c == current_category %}
				<li class="nav-item">
					<a class="nav-link active" href="{% url 'rango:show_category' c.slug %}">
						<span data-feather="archive"></span>{{ c.name }}
					</a>
				</li>
			{% else %}
			<li class="nav-item">
				<a class="nav-link" href="{% url 'rango:show_category' c.slug %}">
					<span data-feather="archive"></span>{{ c.name }}
				</a>
			</li>
			{% endif %}
		{% endfor %}
	{% else %}
	<li class="nav-item">There are no categories present</li>
	{% endif %}
</ul>

templates/rango/category.html
{% extends 'rango/base.html' %}
{% load staticfiles %}

{% block title_block %}
	{% if category %}
		{{ category.name }}
	{% else %}
		Unknown Category
	{% endif %}
{% endblock %}

{% block body_block%}
{% if category %}
	<h1>{{category.name}}</h1> <br/>
	<div>
		<strong id="like_count">{{category.likes}}</strong> likes
		{% if user.is_authenticated %}
  		<button id="like_btn"
  		  data-categoryid="{{ category.id }}"
		  class="btn btn-primary btn-sm"
		  type="button">
	  	<span data-feather="thumbs-up"></span>
		Like Category
   		</button>
		{% endif %}
	</div>
	{% if pages %}
	<ul>
		{% for page in pages %}
		<li>
			<a href="{% url 'rango:goto' %}?page_id={{page.id}}">{{page.title}}</a>
			{% if page.views > 1%}
				<p>page view: {{page.views}} views</p>
			{% elif page.views == 1 %}
				<p>page view: {{page.views}} view</p>
			{% else %}
			<p>page view: {{page.views}} views</p>
			{% endif %}
		</li>
		{% endfor %}
	</ul>
  {% if user.is_authenticated %}
    <div class="jumbotron p-4">
		<div class="container">
			<h1 class="jumbotron-heading">Search with Rango</h1>
		</div>
	</div>
	<div>
		<form action="{% url 'rango:show_category' category.slug %}" class="form-inline" method="post" id="user-form">
			{% csrf_token %}
			<div class="form-group">
				<input type="text" class="form-control" type="text" size="50" name="query" id="query" value="{{query}}"/>
			</div>
	
			<button class="btn btn-primary" type="submit" name="submit">Search</button>
		</form>
	</div>
	<div>
		{% if result_list %}
		<h2>Results</h2>
		<div class="list-group">
			{% for result in result_list %}
			<div class="list-group-item">
				<h3 class="list-group-item-heading">
					<a href="{% url 'rango:goto' %}?page_id={{result.id}}">
						{{ result.title|safe|escape }}
					</a>
				</h3>
			</div>
			{% endfor %}
		</div>
		{% endif %}
	</div>
	{% endif %}	
	{% else %}
		<strong>No pages currently in category.</strong><br />
	{% endif %}
	{% if user.is_authenticated %}
	<a href="{% url 'rango:add_page' category.slug %}">Add Page</a><br />
	{% else %}
	{% endif %}
{% else %}
	<strong>The specified category does not exist. </strong>
{% endif %}
{% endblock %}

templates/rango/login.html
{% extends 'rango/base.html' %}
{% load staticfiles %}

{% block title_block %}
Login
{% endblock %}

{% block body_block %}
<h1>Login to Rango</h1>
<form id="login_form" method="post" action="{% url 'rango:login' %}">
	{% csrf_token %}
	Username: <input type="text" name="username" value="" size="50" />
	<br />
	Password: <input type="password" name="password" value="" size="50" />
	<br />
	<input type="submit" value="submit" />
</form>
{% endblock%}

templates/rango/restricted.html
{% extends 'rango/base.html' %}
{% load staticfiles %}

{% block title_block %}
Restricted Page
{% endblock %}

{% block body_block %}
<p>Since you're logged in, you can see this text</p>
{% endblock%}